# Generated by Django 2.2.12 on 2020-04-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profiles',
            name='image',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
