# Generated by Django 2.2.12 on 2020-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profiles',
            name='image',
            field=models.ImageField(blank=True, default='user/default.jpg', upload_to='user'),
        ),
    ]
