# Generated by Django 2.2.12 on 2020-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotes',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
